# Generated by Django 5.0.6 on 2024-05-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("GRAMS", "GRAMS"),
                            ("KILOGRAMS", "KILOGRAMS"),
                            ("LITERS", "LITERS"),
                            ("TEASPOONS", "TEASPOONS"),
                            ("TABLESPOONS", "TABLESPOONS"),
                            ("CUPS", "CUPS"),
                            ("OUNCES", "OUNCES"),
                            ("POUNDS", "POUNDS"),
                            ("PIECES", "PIECES"),
                            ("NOT SPECIFIED", "NOT SPECIFIED"),
                        ],
                        default="NOT SPECIFIED",
                        max_length=20,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
