# Generated by Django 5.0.6 on 2024-05-27 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_ingredient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instructions",
            new_name="Instruction",
        ),
        migrations.RenameField(
            model_name="instruction",
            old_name="instructions_text",
            new_name="instruction_text",
        ),
    ]
